#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHEXZUDSJrgks+O4NTd1ka+IDeXI5LwlzKTG+T10qcdpfCHY1WTD/ZY2FURYwy2f0ysHBq4gKqCihfE0G3a36Y7btkl5mtu3LCHLy7db8jc6IlI45CVHEOc5Y01JV6f0DRVwzYIg4tGa33+ASFfTUBsv6rXwGNAEDRN0r0hGgxEF3VW1KIvuiHt8ueSUr7FP+vqf0owkzzZvBiiLQX8Oy14JH/ESUO2vdlFk9ZgJd043pA9j0nFBq7g9CkH0MSATfr89e8psbHkgdpB7fnDsW0F12e3pZoBQhikd2KeELyA/dJi+YJy0lMpdd0mbcgAB7uOl3zW7/BBLzkz2itMFnv ntlartey@MacBook-Pro 
